<!-- src/lib/components/AerospaceImpact.svelte -->
<!-- Displays the potential impacts of space weather on different sectors. -->
<script lang="ts">
	// Import child components (currently unused directly here, but kept for potential future use)
	// import RiskIndicator from './RiskIndicator.svelte';
	// import Tooltip from './Tooltip.svelte';

	// Define the expected structure for the 'data' prop, matching the API response.
	export let data: {
		satelliteOperations: string; // Impact text for satellite operations
		aviationCommunication: string; // Impact text for aviation/GPS
		powerGrids: string; // Impact text for power grids
		humanSpaceflight: string; // Impact text for astronauts/space missions
	};

	/**
	 * Finds risk level keywords (None, Low, Moderate, High, Severe, Extreme) within the text
	 * and wraps them in a <strong> tag with appropriate Tailwind CSS color classes.
	 * Uses a case-insensitive regex.
	 * @param text The input string describing potential impacts.
	 * @returns An HTML string with risk levels highlighted.
	 */
	function highlightRisk(text: string): string {
		if (!text) return 'N/A'; // Return 'N/A' if the input text is empty or null

		// Regex to find risk level keywords (case-insensitive)
		const riskRegex = /(Extreme|Severe|High|Moderate|Low|None)/gi;

		// Replace found keywords with styled HTML spans
		return text.replace(riskRegex, (match) => {
			const lowerMatch = match.toLowerCase();
			let colorClass = ''; // Tailwind classes for styling

			// Assign color and font weight based on the risk level
			switch (lowerMatch) {
				case 'extreme':
					colorClass = 'text-red-600 dark:text-red-500 font-bold';
					break;
				case 'severe':
					colorClass = 'text-red-500 dark:text-red-400 font-bold';
					break;
				case 'high':
					colorClass = 'text-orange-500 dark:text-orange-400 font-semibold';
					break;
				case 'moderate':
					colorClass = 'text-yellow-500 dark:text-yellow-400 font-semibold';
					break;
				case 'low':
					colorClass = 'text-green-500 dark:text-green-400 font-medium';
					break;
				case 'none':
				default:
					colorClass = 'text-gray-500 dark:text-gray-400 font-normal';
					break; // Use a neutral color for 'None'
			}
			// Return the matched word wrapped in a strong tag with the determined classes
			return `<strong class="${colorClass}">${match}</strong>`;
		});
	}

	// Simple emoji icons for different impact categories
	const icons = {
		satellite: '🛰️',
		aviation: '✈️',
		power: '⚡',
		astronaut: '👩‍🚀'
	};
</script>

<!-- Card container -->
<div class="overflow-hidden rounded-lg bg-white shadow-lg dark:bg-gray-800">
	<div class="p-5 sm:p-6">
		<!-- Card Title -->
		<h2 class="mb-4 text-xl font-semibold text-gray-900 dark:text-gray-100">
			Potential Impacts Explained
		</h2>
		<!-- List of impact categories -->
		<div class="space-y-5">
			<!-- Satellite Operations Impact -->
			<div class="flex items-start">
				<span class="mr-3 mt-1 flex-shrink-0 text-2xl" aria-hidden="true">{icons.satellite}</span>
				<div>
					<h3 class="mb-1 font-medium text-gray-700 dark:text-gray-200">Satellite Operations</h3>
					<!-- Use {@html ...} to render the HTML generated by highlightRisk -->
					<p class="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
						{@html highlightRisk(data.satelliteOperations)}
					</p>
				</div>
			</div>

			<!-- Aviation & GPS Impact -->
			<div class="flex items-start">
				<span class="mr-3 mt-1 flex-shrink-0 text-2xl" aria-hidden="true">{icons.aviation}</span>
				<div>
					<h3 class="mb-1 font-medium text-gray-700 dark:text-gray-200">Aviation & GPS</h3>
					<p class="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
						{@html highlightRisk(data.aviationCommunication)}
					</p>
				</div>
			</div>

			<!-- Power Grids Impact -->
			<div class="flex items-start">
				<span class="mr-3 mt-1 flex-shrink-0 text-2xl" aria-hidden="true">{icons.power}</span>
				<div>
					<h3 class="mb-1 font-medium text-gray-700 dark:text-gray-200">Power Grids</h3>
					<p class="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
						{@html highlightRisk(data.powerGrids)}
					</p>
				</div>
			</div>

			<!-- Human Spaceflight Impact -->
			<div class="flex items-start">
				<span class="mr-3 mt-1 flex-shrink-0 text-2xl" aria-hidden="true">{icons.astronaut}</span>
				<div>
					<h3 class="mb-1 font-medium text-gray-700 dark:text-gray-200">Human Spaceflight</h3>
					<p class="text-sm leading-relaxed text-gray-600 dark:text-gray-400">
						{@html highlightRisk(data.humanSpaceflight)}
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
